#scatterplot work for 5/15/20
scenario1_named<- read.csv('./scenario1_result_named.csv')
#note, data is not in acrefeet, as the labels imply
#View(scenario1)

library(dplyr)
ALclustered<-select(scenario1_named, matches("AL"))
ALclustered<-cbind(ALclustered, rowMeans(ALclustered))
ALclustered<-cbind(ALclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

CHclustered<-select(scenario1_named, matches("CH"))
CHclustered<-cbind(CHclustered, rowMeans(CHclustered))
CHclustered<-cbind(CHclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

CYclustered<-select(scenario1_named, matches("CY"))
CYclustered<-cbind(CYclustered, rowMeans(CYclustered))
CYclustered<-cbind(CYclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

HAclustered<-select(scenario1_named, matches("HA"))
HAclustered<-cbind(HAclustered, rowMeans(HAclustered))
HAclustered<-cbind(HAclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

LWclustered<-select(scenario1_named, matches("LW"))
LWclustered<-cbind(LWclustered, rowMeans(LWclustered))
LWclustered<-cbind(LWclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

LRclustered<-select(scenario1_named, matches("LR"))
LRclustered<-cbind(LRclustered, rowMeans(LRclustered))
LRclustered<-cbind(LRclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

OPclustered<-select(scenario1_named, matches("OP"))
OPclustered<-cbind(OPclustered, rowMeans(OPclustered))
OPclustered<-cbind(OPclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

SRclustered<-select(scenario1_named, matches("SR"))
SRclustered<-cbind(SRclustered, rowMeans(SRclustered))
SRclustered<-cbind(SRclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

SHclustered<-select(scenario1_named, matches("SH"))
SHclustered<-cbind(SHclustered, rowMeans(SHclustered))
SHclustered<-cbind(SHclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

VVclustered<-select(scenario1_named, matches("VV"))
VVclustered<-cbind(VVclustered, rowMeans(VVclustered))
VVclustered<-cbind(VVclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

VCclustered<-select(scenario1_named, matches("VC"))
VCclustered<-cbind(VCclustered, rowMeans(VCclustered))
VCclustered<-cbind(VCclustered, scenario1_named$obj0, scenario1_named$obj1, scenario1_named$obj2, scenario1_named$obj3)

#scenario1 v objective 0
plot(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: AL')
cor(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj0`)
plot(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: CH')
cor(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj0`)
plot(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: CY')
cor(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj0`)
plot(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: HA')
cor(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj0`)
plot(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: LR')
cor(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj0`)
plot(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: LW')
cor(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj0`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj0`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj0`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj0`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj0`)
plot(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: SR')
cor(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj0`)
plot(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: VC')
cor(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj0`)
plot(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj0`,  xlab = 'Mean Pumpage', ylab = 'Objective 0', main = 'Scenario 1: VV')
cor(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj0`)

#scenario1 objective 1
plot(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: AL')
cor(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj1`)
plot(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: CH')
cor(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj1`)
plot(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: CY')
cor(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj1`)
plot(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: HA')
cor(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj1`)
plot(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: LR')
cor(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj1`)
plot(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: LW')
cor(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj1`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj1`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj1`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj1`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj1`)
plot(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: SR')
cor(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj1`)
plot(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: VC')
cor(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj1`)
plot(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj1`,  xlab = 'Mean Pumpage', ylab = 'Objective 1', main = 'Scenario 1: VV')
cor(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj1`)

#scenario1 v objective 2
plot(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: AL')
cor(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj2`)
plot(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: CH')
cor(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj2`)
plot(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: CY')
cor(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj2`)
plot(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: HA')
cor(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj2`)
plot(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: LR')
cor(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj2`)
plot(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: LW')
cor(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj2`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj2`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj2`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj2`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj2`)
plot(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: SR')
cor(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj2`)
plot(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: VC')
cor(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj2`)
plot(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj2`,  xlab = 'Mean Pumpage', ylab = 'Objective 2', main = 'Scenario 1: VV')
cor(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj2`)

#scenario1 v objective 3
plot(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: AL')
cor(ALclustered$`rowMeans(ALclustered)`,ALclustered$`scenario1_named$obj3`)
plot(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: CH')
cor(CHclustered$`rowMeans(CHclustered)`,CHclustered$`scenario1_named$obj3`)
plot(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: CY')
cor(CYclustered$`rowMeans(CYclustered)`,CYclustered$`scenario1_named$obj3`)
plot(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: HA')
cor(HAclustered$`rowMeans(HAclustered)`,HAclustered$`scenario1_named$obj3`)
plot(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: LR')
cor(LRclustered$`rowMeans(LRclustered)`,LRclustered$`scenario1_named$obj3`)
plot(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: LW')
cor(LWclustered$`rowMeans(LWclustered)`,LWclustered$`scenario1_named$obj3`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj3`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj3`)
plot(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: OP')
cor(OPclustered$`rowMeans(OPclustered)`,OPclustered$`scenario1_named$obj3`)
plot(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: SH')
cor(SHclustered$`rowMeans(SHclustered)`,SHclustered$`scenario1_named$obj3`)
plot(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: SR')
cor(SRclustered$`rowMeans(SRclustered)`,SRclustered$`scenario1_named$obj3`)
plot(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: VC')
cor(VCclustered$`rowMeans(VCclustered)`,VCclustered$`scenario1_named$obj3`)
plot(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj3`,  xlab = 'Mean Pumpage', ylab = 'Objective 3', main = 'Scenario 1: VV')
cor(VVclustered$`rowMeans(VVclustered)`,VVclustered$`scenario1_named$obj3`)

